#!/bin/bash
set -e

# --- FUNCTIONS ---
usage() {
    echo "Usage: $0 <host> [auth]"
    echo "  index-name: The name of an index to detach form event gathering schema system."
    echo "  host: Elasticsearch host (e.g. http://localhost:9200 or https://es:9200)"
    echo "  auth: Optional <username:password>"
    exit 1
}

# --- ARGUMENT HANDLING ---
INDEX="$1"
OLD_INDEX="old-$1"
HOST="$2"
AUTH="$3"

if [[ -z "$INDEX" || -z "$HOST" ]]; then
    usage
fi

if [[ -n "$AUTH" && "$AUTH" != *:* ]]; then
    echo "Auth must contain a colon (username:password)."
    exit 1
fi

# --- CURL SWITCHES ---
CURL_OPTS='-sS -w \n%{http_code}'
if [[ "$HOST" == https* ]]; then
    CURL_OPTS="$CURL_OPTS -k"
fi
if [[ -n "$AUTH" ]]; then
    CURL_OPTS_T="$CURL_OPTS -u $AUTH"
    CURL_OPTS_P="$CURL_OPTS -u '$AUTH'"
fi

echo "curl $CURL_OPTS_P -X POST $HOST/$INDEX/_ilm/remove"
response=$(curl $CURL_OPTS_T -X POST "$HOST/$INDEX/_ilm/remove")
http_code=$(echo "$response" | tail -n1)
body=$(echo "$response" | sed '$d')
if [ "$http_code" -lt 200 ] || [ "$http_code" -ge 300 ]; then
  echo -e "Curl failed (status $http_code): \n$body"
  exit 1
fi

echo "curl $CURL_OPTS_P -X DELETE $HOST/$INDEX/_alias/event"
response=$(curl $CURL_OPTS_T -X DELETE "$HOST/$INDEX/_alias/event")
http_code=$(echo "$response" | tail -n1)
body=$(echo "$response" | sed '$d')
if [ "$http_code" -lt 200 ] || [ "$http_code" -ge 300 ]; then
  echo -e "Curl failed (status $http_code): \n$body"
fi

echo "curl $CURL_OPTS_P -X PUT $HOST/$OLD_INDEX -d'{\"settings\":{\"number_of_replicas\":0}}' -H 'Content-Type: application/json'"
response=$(curl $CURL_OPTS_T -X PUT "$HOST/$OLD_INDEX" -d "{\"settings\":{\"number_of_replicas\":0}}" -H 'Content-Type: application/json')
http_code=$(echo "$response" | tail -n1)
body=$(echo "$response" | sed '$d')
if [ "$http_code" -lt 200 ] || [ "$http_code" -ge 300 ]; then
  echo -e "Curl failed (status $http_code): \n$body"
  exit 1
fi

echo "curl $CURL_OPTS_P -X POST $HOST/_reindex -d'{\"source\":{\"index\": \"$INDEX\"},\"dest\":{\"index\":\"$OLD_INDEX\"}}' -H 'Content-Type: application/json'"
response=$(curl $CURL_OPTS_T -X POST "$HOST/_reindex" -d "{\"source\":{\"index\":\"$INDEX\"},\"dest\":{\"index\":\"$OLD_INDEX\"}}" -H 'Content-Type: application/json')
http_code=$(echo "$response" | tail -n1)
body=$(echo "$response" | sed '$d')
if [ "$http_code" -lt 200 ] || [ "$http_code" -ge 300 ]; then
  echo -e "Curl failed (status $http_code): \n$body"
  exit 1
fi

echo "curl $CURL_OPTS_P -X DELETE $HOST/$INDEX"
response=$(curl $CURL_OPTS_T -X DELETE "$HOST/$INDEX")
http_code=$(echo "$response" | tail -n1)
body=$(echo "$response" | sed '$d')
if [ "$http_code" -lt 200 ] || [ "$http_code" -ge 300 ]; then
  echo -e "Curl failed (status $http_code): \n$body"
  exit 1
fi
