quarkus:
  log:
    category:
      "org.apache.shiro":
        level: WARN
      "com.dropchop":
        level: DEBUG
  index-dependency:
    recyclone-mapper-jpa:
      group-id: com.dropchop.recyclone
      artifact-id: recyclone-mapper-jpa
    recyclone-mapper-es:
      group-id: com.dropchop.recyclone
      artifact-id: recyclone-mapper-es
    recyclone-repo-jpa-blaze:
      group-id: com.dropchop.recyclone
      artifact-id: recyclone-repo-jpa-blaze
    recyclone-repo-es:
      group-id: com.dropchop.recyclone
      artifact-id: recyclone-repo-es
    recyclone-service-common:
      group-id: com.dropchop.recyclone
      artifact-id: recyclone-service-common
    recyclone-service-jpa:
      group-id: com.dropchop.recyclone
      artifact-id: recyclone-service-jpa
    recyclone-service-es:
      group-id: com.dropchop.recyclone
      artifact-id: recyclone-service-es

  rest:
    path: /api
  swagger-ui:
    path: /api/spec/ui
    always-include: true
  smallrye-openapi:
    path: /api/spec/openapi
    operation-id-strategy: package-class-method
  datasource:
    db-kind: postgresql
    username: recyclone_test
    password: recyclone_test
  elasticsearch:
    devservices:
      enabled: true
      port: 9300


    # uncomment for native image build
    #jdbc:
    #  url: jdbc:postgresql://localhost:5432/recyclone_test
    #  max-size: 16

  hibernate-orm:
    database:
      generation: drop-and-create
    sql-load-script: dev-import.sql
    packages:
      - com.blazebit.persistence.impl.function.entity
      - com.dropchop.recyclone.model.api
      - com.dropchop.recyclone.model.api.marker
      - com.dropchop.recyclone.model.api.localization
      - com.dropchop.recyclone.model.api.security
      - com.dropchop.recyclone.model.entity.jpa
      - com.dropchop.recyclone.model.entity.jpa.localization
      - com.dropchop.recyclone.model.entity.jpa.security
      - com.dropchop.recyclone.quarkus.it.model.entity.jpa

  recyclone:
    test: neki
    rest:
      info:
        title: "Recyclone API"
        version: ${project.version}
        contact:
          name: "Recyclone API Support"
          url: "https://exampleurl.com/contact"
          email: "techsupport@example.com"
        license:
          name: "Apache 2.0"
          url: "https://www.apache.org/licenses/LICENSE-2.0.html"
      security:
        ApiKey:
          type: http
          scheme: bearer
        BasicAuth:
          type: http
          scheme: basic
        ApiKeyAuth:
          type: apiKey
          in: header
          api-key-name: apiKeyName
        JWT:
          type: http
          scheme: bearer
          bearer-format: JWT
      includes:
        - "com.dropchop.recyclone.quarkus.it.rest.api.*"
        - "*.localization.*"
        - "*.tagging.*"
        - "*.security.*"

    # this config is actually not needed, but is here to showcase
    injection-points-config:
      target-qualifier: <same-as-dependant>
      fallback-qualifier: recyclone_default
      match-dependants:
        - match: "*.localization.*"
          target-qualifier: recyclone_default
        - match: DummyResource
          target-qualifier: recyclone_default
          match-dependencies:
            - match: DummyService
              target-qualifier: alter
        - match: DummyService
          target-qualifier: <same-as-dependant>
