quarkus:
  log:
    category:
      "org.apache.shiro":
        level: WARN
      "com.dropchop":
        level: DEBUG

  datasource:
    db-kind: postgresql
    username: recyclone
    password: recyclone
    devservices:
      port: 35432
      db-name: recyclone_dev

  elasticsearch:
    devservices:
      port: 9200

  hibernate-orm:
    #log:
    #  sql: true
    #  bind-parameters: true
    database:
      generation: drop-and-create
    sql-load-script: dev-import.sql

dropchop:
#  service-type:
#    LanguageService: "rcyn_default"
