quarkus:
  http:
    port: 24088

  log:
    category:
      "org.apache.shiro":
        level: WARN
      "com.dropchop":
        level: DEBUG

  compose:
    devservices:
      ryuk-enabled: false
      remove-volumes: false
      files: src/main/docker/compose-devservices-dev.yaml

  hibernate-orm:
    #log:
    #  sql: true
    #  bind-parameters: true
    database:
      generation: update

dropchop:
#  service-type:
#    LanguageService: "rcyn_default"
