quarkus:
  log:
    category:
      "org.apache.shiro":
        # noinspection QsYaml
        level: WARN
      "com.dropchop":
        # noinspection QsYaml
        level: DEBUG
  index-dependency:
    recyclone-base-jpa-mapper:
      group-id: com.dropchop.recyclone
      artifact-id: recyclone-base-jpa-mapper
    recyclone-base-jpa-repo:
      group-id: com.dropchop.recyclone
      artifact-id: recyclone-base-jpa-repo
    recyclone-base-jpa-service:
      group-id: com.dropchop.recyclone
      artifact-id: recyclone-base-jpa-service
    recyclone-base-es-mapper:
      group-id: com.dropchop.recyclone
      artifact-id: recyclone-base-es-mapper
    recyclone-base-es-repo:
      group-id: com.dropchop.recyclone
      artifact-id: recyclone-base-es-repo
    recyclone-base-es-service:
      group-id: com.dropchop.recyclone
      artifact-id: recyclone-base-es-service

    recyclone-events-es-model:
      group-id: com.dropchop.recyclone
      artifact-id: recyclone-events-es-model
    recyclone-events-es-mapper:
      group-id: com.dropchop.recyclone
      artifact-id: recyclone-events-es-mapper
    recyclone-events-es-repo:
      group-id: com.dropchop.recyclone
      artifact-id: recyclone-events-es-repo
    recyclone-events-api-service:
      group-id: com.dropchop.recyclone
      artifact-id: recyclone-events-api-service
    recyclone-events-es-service:
      group-id: com.dropchop.recyclone
      artifact-id: recyclone-events-es-service
    recyclone-events-api-jaxrs-internal:
      group-id: com.dropchop.recyclone
      artifact-id: recyclone-events-api-jaxrs-internal
    recyclone-events-jaxrs-internal:
      group-id: com.dropchop.recyclone
      artifact-id: recyclone-events-jaxrs-internal

  rest:
    path: /api
  swagger-ui:
    path: /api/spec/ui
    always-include: true
  smallrye-openapi:
    path: /api/spec/openapi
    operation-id-strategy: package-class-method

  hibernate-orm:
    #log:
    #  sql: true
    #  bind-parameters: true
    database:
      generation: update
    packages:
      - com.blazebit.persistence.impl.function.entity
      - com.dropchop.recyclone.base.api.model
      - com.dropchop.recyclone.base.api.model.marker
      - com.dropchop.recyclone.base.api.model.localization
      - com.dropchop.recyclone.base.api.model.security
      - com.dropchop.recyclone.base.jpa.model.base
      - com.dropchop.recyclone.base.jpa.model.attr
      - com.dropchop.recyclone.base.jpa.model.marker
      - com.dropchop.recyclone.base.jpa.model.common
      - com.dropchop.recyclone.base.jpa.model.localization
      - com.dropchop.recyclone.base.jpa.model.security
      - com.dropchop.recyclone.base.jpa.model.tagging
      - com.dropchop.recyclone.quarkus.it.model.entity.jpa

  recyclone:
    test: neki
    rest:
      info:
        title: "Recyclone API"
        version: ${project.version}
        contact:
          name: "Recyclone API Support"
          url: "https://exampleurl.com/contact"
          email: "techsupport@example.com"
        license:
          name: "Apache 2.0"
          url: "https://www.apache.org/licenses/LICENSE-2.0.html"
      security:
        client-access-keys:
          my-recyclone-key:
            secret: Gs*t4USB29uAMVex!vmRJ#8g6jt^cq3n
            salt: QqvBbrGSFVAVAd9*
          my-other-client-key:
            secret: 2cDYw%BKSK4bD9zk^^FE%z$y7mbeX8wj
            salt: ymCY6BrfPPxv1MX$

        mechanisms:
          - mechanism: bearer-token
          - mechanism: basic-auth
          - mechanism: api-key
            header-name: X-Recyclone-API-Key
            query-name: x-recyclone-api-key
          - mechanism: jwt
            secret: 26dx0wLJMZRwUWPDeLNFqnAUem5qAKrzNmxLAvBgE78u36DhBv1pAq0zH36M4qKy1yncXgCPBpJdX1CNfweB5Zx6uHptPxGB92ZfRPKUewAPmNpHLmBUZcypL7YXbrDH4zWUgV877CciMAy9425P3vmGjy0NPpFdy7bT2vVEvhjDb501iq1Q0tW3iXhVh1CFCxPGfaFfuE3tzvg6qSYmP6xNrFKkNEfP3aTWRwt5pud8PqyLrBbcGn5Sf4JCV1ac
            issuer: Dropchop d.o.o.
            timeout-seconds: 900
      includes:
        - "com.dropchop.recyclone.quarkus.it.rest.api.*"
        - "*.localization.*"
        - "*.tagging.*"
        - "*.security.*"
        - "*.events.*"

    # this config is actually not needed but is here to showcase
    injection-points-config:
      target-qualifier: <same-as-dependant>
      fallback-qualifier: recyclone_default
      match-dependants:
        - match: "*.localization.*"
          target-qualifier: recyclone_default
        - match: DummyResource
          target-qualifier: recyclone_default
          match-dependencies:
            - match: DummyService
              target-qualifier: alter
        - match: DummyResourceInternal
          target-qualifier: recyclone_default
          match-dependencies:
            - match: DummyService
              target-qualifier: alter
        - match: DummyService
          target-qualifier: <same-as-dependant>

