quarkus:
  log:
    category:
      "org.apache.shiro":
        level: WARN
      "com.dropchop":
        level: DEBUG
  index-dependency:
    recyclone-repo-jpa-blaze:
      group-id: com.dropchop.recyclone
      artifact-id: recyclone-repo-jpa-blaze
    recyclone-service-jpa:
      group-id: com.dropchop.recyclone
      artifact-id: recyclone-service-jpa
  rest:
    path: /api
  swagger-ui:
    path: /api/spec/ui
    always-include: true
  smallrye-openapi:
    path: /api/spec/openapi
    operation-id-strategy: package-class-method
  datasource:
    db-kind: postgresql
    username: recyclone_test
    password: recyclone_test

    # uncomment for native image build
    #jdbc:
    #  url: jdbc:postgresql://localhost:5432/recyclone_test
    #  max-size: 16

  hibernate-orm:
    database:
      generation: drop-and-create
    sql-load-script: dev-import.sql
    packages:
      - com.blazebit.persistence.impl.function.entity
      - com.dropchop.recyclone.model.api
      - com.dropchop.recyclone.model.api.marker
      - com.dropchop.recyclone.model.api.localization
      - com.dropchop.recyclone.model.api.security
      - com.dropchop.recyclone.model.entity.jpa
      - com.dropchop.recyclone.model.entity.jpa.localization
      - com.dropchop.recyclone.model.entity.jpa.security
      - com.dropchop.recyclone.quarkus.it.model.entity.jpa

  recyclone:
    test: neki
    rest:
      info:
        title: "Recyclone API"
        version: ${project.version}
        contact:
          name: "Recyclone API Support"
          url: "https://exampleurl.com/contact"
          email: "techsupport@example.com"
        license:
          name: "Apache 2.0"
          url: "https://www.apache.org/licenses/LICENSE-2.0.html"
      # noinspection QsYaml
      security:
        ApiKey:
          type: http
          scheme: bearer
        BasicAuth:
          type: http
          scheme: basic
        ApiKeyAuth:
          type: apiKey
          in: header
          api-key-name: apiKeyName
        JWT:
          type: http
          scheme: bearer
          bearer-format: JWT
      includes:
        - "com.dropchop.recyclone.quarkus.it.rest.api.*"
        - "*.localization.*"
        - "*.tagging.*"
        - "*.security.*"
    service:
      qualifier: recyclone_jpa_default
      LanguageService:
        qualifier: recyclone_jpa_default
      DummyService:
        qualifier: alter
